spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
#  admin setting is used to create topic from spring-boot app
---
spring:
  profiles: nonprod
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        # SSL Auth
        trust-store-location: file:/Udemy/KAFKA/SSL/client.truststore.jks
        trust-store-password: 123456
        #key-store-location,password is provided for 2-way Auth
        key-store-location: file:/Udemy/KAFKA/SSL/client.keystore.jks
        key-store-password: 123456
      properties:
        acks: all
        retries: 10
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:


---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer